### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Tarsnap/libcperciva#2]
I would like to point out that identifiers like "[`_CRYPTO_ENTROPY_H_`](https://github.com/Tarsnap/libcperciva/blob/7fa82d049b72f6abbdcf166ead8b2db92cde97e6/crypto/crypto_entropy.h#L1)" and "[`_DAEMONIZE_H_`](https://github.com/Tarsnap/libcperciva/blob/7fa82d049b72f6abbdcf166ead8b2db92cde97e6/util/daemonize.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by cperciva** [comment]
This isn't C++ code, so your complaint is somewhat misdirected.  But the real answer is that I chose to follow the de facto standard rather than the de jure standard, and if this breaks anything it will show up as build breakage rather than runtime breakage.

So I'm marking this as wontfix unless you can demonstrate a platform where this code actually causes problems.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by cperciva** [comment]
There's undefined behaviour, and then there's undefined behaviour.  This is the sort which is harmless.

**Comment by elfring** [comment]
I prefer such source files which [do not tamper with the reserved name space](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
Should your software be only reused for the implementation of a compiler for the programming language "C" (or "C++")?

**Comment by cperciva** [comment]
So... don't use my code?
