### ISSUE TITLE
ERANGE in parsenum is interpreted as "result too large"

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/libcperciva#236]
Code like
```
PARSENUM(intvar, "1", 10, 20);
warnp("arg error");
```

produces
```
scrypt: arg error 1: Result too large
```
when I'd expect it to be "Result too small".

That's because we use `ERANGE` in `util/parsenum.h`, which is interpreted by the system as "Result too large" [1].  Actually, POSIX even gives the same string[2].
[1] https://github.com/freebsd/freebsd/blob/master/sys/sys/errno.h#L91
[2] https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/errno.h.html

At first glance, it doesn't look like the C standard has this mistake; as far as I can tell, `ERANGE` is just the value of `errno` that functions like `strtol` can set.

**Comment by cperciva** [comment]
Yes.  On some systems ERANGE is documented as "Result too large or too small"; in others it's documented as "Result out of range".

But we should use ERANGE anyway, because on systems which localize strerror it will be translated to the appropriate language.
