### ISSUE TITLE
tests/{md5, sha1}

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/libcperciva#263]
We have tests/sha256 but not tests/md5 or tests/sha1.  These aren't critical but it's probably worth having them -- I noticed the absence of md5 when I wanted to check the performance of a system.

I created a branch with the MD5 code, but it needs to be hooked into the build/test framework:

https://github.com/Tarsnap/libcperciva/tree/tests-md5

**Comment by gperciva** [comment]
Fixed in #264 #267 .
