### ISSUE TITLE
inconsistency in function names in comments

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/libcperciva#275]
I tend to refer to funcname() in comments, because that's a huge visual reminder that it's a function rather than a random noun.  Many older comments just refer to funcname, without parentheses.

I should probably consistencyify this.  Which do you prefer?

**Comment by gperciva** [comment]
FWIW, POSIX uses *italics* and (parentheses) to denote known function names, and just *italics* to denote function pointers.  For example,

> The *atexit*() function shall register the function pointed to by *func*, to be called...
> https://pubs.opengroup.org/onlinepubs/9699919799/functions/atexit.html

My preference is to not have the italics (because writing `*blah()*` or `/blah()/` looks weird in text), but to use parentheses.

**Comment by cperciva** [comment]
I'm fine with standardizing on using parentheses.

**Comment by gperciva** [comment]
Fixed in #286.
