### ISSUE TITLE
automatically collect cpusupport CFLAGS

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/libcperciva#371]
The 

```
cflags-foo.o:
	@echo '$${CFLAGS_FOO_BAR}'
```

notations are starting to get a bit unwieldy, and I worry that it may also end up becoming error-prone once there's a large number of them.

I'm wondering if we should have something along the lines of

```
/**
 * CPUSUPPORT CFLAGS: FOO_BAR FOO_BAZ
 */
```

in the relevant C source, and have `metabuild.sh` do something like `CF=$(grep 'CPUSUPPORT CFLAGS:' $S | cut -f 2- -d : | while read X; do printf "$${CFLAGS_%s}\n" "$X"; done)` instead of the current `$(${MAKEBSD} cflags-${F})`.

**Comment by cperciva** [comment]
@gperciva If you have time at some point, can you try implementing this so I can see how much it cleans up (or not) the tree?

**Comment by gperciva** [comment]
Can do... but a failure to add the correct CFLAGS_FOO_BAR will just be a compile failure [1], and thus easily noticeable.  If not with a plain old `make`, then at least in the github Action with `clang -Weverything -Werror`.

[1] at least, if the file uses the relevant intrinsics.  Admittedly in `master` at the very moment, `sha256_sse2.c` doesn't use any such intrinsics, but we'd run into compile failures as soon as we start to use them.  Source: personal experience from a few days ago.  :)

**Comment by gperciva** [comment]
Also, I must admit that in that particular case, the problem was that I'd forgotten to update `tests/aws/Makefile.BSD`, which wasn't an obvious place to look when working on `sha256_sse2.c`.  So this system would have saved me some time.

**Comment by cperciva** [comment]
It will result in a compilation failure -- on systems with the relevant compiler support.  If we forget the cflags needed for an ARM-optimized file, it will still compile just fine on x86 since after preprocessing it will be empty.

I'd like to avoid the potential for doing a release which fails to compile on some systems.
