### ISSUE TITLE
Duplicative compiling

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/libcperciva#383]
This isn't particularly a libcperciva issue, but I'm opening it here because this is where all the build infrastructure originates.  In kivaloo we now have a nontrivial number of binaries, and right now each of them rebuilds the objects they need from the library code.  At some point we should do something about this.

**Comment by gperciva** [comment]
I thought that was deliberate!  Ok, I'll work on this.

**Comment by gperciva** [comment]
Note to myself: it's not absolutely trivial, because in very occasional situations we want to compile a library object with different defines.  For example, `spiped/perftests/standalone-enc` needs to add `-DSTANDALONE_ENC_TESTING` to `proto-crypt.o`.

**Comment by cperciva** [comment]
It was deliberate... when we didn't have many binaries reusing the same objects.  It's particularly annoying in kivaloo since all of the binaries in that project make use of the wire/netbuf/network/events stack.

**Comment by gperciva** [comment]
Before changing things, I figured that I should check on the current state of affairs.  At one point, you wanted `make -f Makefile.BSD` to work.

1. it's currently broken for `spiped/perftests/standalone-enc`, but I have a branch which fixes it.
2. it doesn't work with `cpusupport-config.h`.  I suspect that a fix for this would be messy, particularly if we want that fix to generate `cpusupport-config.h` if it's missing (as we do in the `Makefile`s).  Is it ok to leave this as-is, namely you can still compile a program with `make -f Makefile.BSD` but having no cpusupport?

**Comment by cperciva** [comment]
Yes, that's fine.  The only reason I want `make -f Makefile.BSD` to work is that it's easier for development if I don't have to re-run `make Makefiles` every time I change something.  I don't need optimizations while I'm writing new code (well, unless I'm testing new optimizations, but that's a niche case).
