### ISSUE TITLE
Add strtol replacement

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/libcperciva#4]
The API for strtol is idiotic.  I need to write a wrapper around it which looks at endptr in order to distinguish between "0" and "nothing parsable as an integer here".  Something like OpenBSD's strtonum probably...

**Comment by gperciva** [comment]
Do you want me to look at this?

**Comment by cperciva** [comment]
No, I want to decide what API I want to use for it.  But I may have you go through the trees and use the function once I've written it.

**Comment by cperciva** [comment]
I also need a `double` version of this.  I wonder if I can make a generic `STRTO(optstr, type, min, max)` macro...

**Comment by gperciva** [comment]
After checking

    git grep strt

in our projects, I see the following list:

```
strtol
strtod
stdtoumax
strtoimax
strtoull
```

Probably not relevant is:

```
strtok_r
```

**Comment by cperciva** [comment]
Right, `strtok_r` (and `strtok`) are functions for splitting into fields, not for parsing a string as a value.

Good to know that I use both `strtoimax` and `strtoumax` though... hmm, I guess I'll need to figure out a clean way to handle both signed and unsigned values here.

**Comment by gperciva** [comment]
Incidentally, spiped and kivaloo both have a

```
/* Macro to simplify error-handling in command-line parse loop. */
#define OPT_EPARSE(opt, arg) do {                                       \
        warnp("Error parsing argument: -%c %s", opt, arg);              \
        exit(1);                                                        \
} while (0)
```

**Comment by gperciva** [comment]
At first glance, I'm not certain you actually need signed values.  `strtoimax` is used in:

spiped: `GETOPT_OPTARG("-n")` where `-n` is `<max # connections>`.  I don't think negative values here make sense!

kivaloo: `lbs`, `mux`, and `s3` all seem to have the same `-n`.  (well, `lbs` uses it for `<# of readers>`, but still, a negative value doesn't make sense).  `lbs-s3` uses it for `-b` block size.  `lbs` has `-b` block size, `-l` `<read latency in ns>`, and `-n` `<# of readers`>.

I could dig deeper if you want.

**Comment by cperciva** [comment]
Hmm, it does seem like `opt_n` should be unsigned.  I wonder why I did that.

Still, I'm sure I'll *eventually* need to handle signed integers, so I might as well do it from the start.

**Comment by gperciva** [comment]
This is handled with parsenum, https://github.com/Tarsnap/libcperciva/pull/58 (amongst other PRs).
