### ISSUE TITLE
switch mpool from linked list to stack?

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/libcperciva#5]
At some point I may want to switch mpool to using a stack of free allocations instead of a linked list -- reducing the pointer chasing might improve performance.  I'm not sure though; I need to try it and run benchmarks (probably in kivaloo since that's a major mpool user).

I'm opening this issue as a note to myself that I should investigate this at some point.

**Comment by gperciva** [comment]
This is handled in #77 (or maybe the "adjusted" version, #80).
