### ISSUE TITLE
crypto_aesctr_free should probably use insecure_memzero

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/libcperciva#8]
libcperciva/crypto/crypto_aesctr.c
line 82
```
void
crypto_aesctr_free(struct crypto_aesctr * stream)
{
        int i;

        /* Be compatible with free(NULL). */
        if (stream == NULL)
                return;

        /* Zero potentially sensitive information. */
        for (i = 0; i < 16; i++)
                stream->buf[i] = 0;
        stream->bytectr = stream->nonce = 0;
```

Should that "zero potentially sensitive information" be replaced with insecure_memzero?  It also happens inside crypto_aesctr_buf (same file).

**Comment by cperciva** [comment]
Yes, that should be insecure_memzero.  In fact, use insecure_memzero to nuke the entire structure here; no need to zero fields separately.

I missed this when I was sprinkling insecure_memzero because I was grepping for memset.

**Comment by gperciva** [comment]
https://github.com/Tarsnap/tarsnap/pull/51

I'm not totally certain whether you wanted a PR for tarsnap or libcperciva, or both.

**Comment by cperciva** [comment]
I'll merge it to tarsnap and then merge it from there to the rest.

**Comment by cperciva** [comment]
Fixed in ca73af77.

**Comment by gperciva** [comment]
Want to grab https://github.com/Tarsnap/tarsnap/commit/769ac56d03ce25a20f6045da335f14af6a33e954 as well?  (remove unused vars)

**Comment by cperciva** [comment]
I'll pick that up in my next round of cross-tree merging.
